HARDWARE_SPECS = {
    "H800_8gpn": {
        "gpu_name": "NVIDIA H800",
        "gpu_memory_gb": 79.65,
        "gpu_count": 8,
        "fp32_tflops": 51.67,
        "fp16_tflops": 754.86,
        "bf16_tflops": 685.76,
        "memory_bandwidth_gbps": 2666.23,
        "host_to_device_bandwidth_gbps": 50.79,
        "device_to_host_bandwidth_gbps": 50.23,
        "intra_node_bandwidth_gbps": 386.43,
        "inter_node_bandwidth_gbps": 46.94,
        "intra_node_latency_us": 1.105,
        "inter_node_latency_us": 11.363,
        "calibrated": True,
        "network_calibrated": True,
        "bf16_curve": {
            "dtype": "bfloat16",
            "peak_tflops": 685.76,
            "fit_a": 0.185718,
            "fit_b": -0.86441,
            "fit_max": 0.9378,
            "points": [
                {
                    "size": 64,
                    "tflops": 0.04,
                    "efficiency": 0.0001,
                    "time_ms": 0.012,
                },
                {
                    "size": 128,
                    "tflops": 0.35,
                    "efficiency": 0.0005,
                    "time_ms": 0.012,
                },
                {
                    "size": 256,
                    "tflops": 2.82,
                    "efficiency": 0.0041,
                    "time_ms": 0.012,
                },
                {
                    "size": 512,
                    "tflops": 22.52,
                    "efficiency": 0.0328,
                    "time_ms": 0.012,
                },
                {
                    "size": 1024,
                    "tflops": 175.19,
                    "efficiency": 0.2555,
                    "time_ms": 0.012,
                },
                {
                    "size": 2048,
                    "tflops": 550.4,
                    "efficiency": 0.8026,
                    "time_ms": 0.031,
                },
                {
                    "size": 4096,
                    "tflops": 764.61,
                    "efficiency": 1.115,
                    "time_ms": 0.18,
                },
                {
                    "size": 8192,
                    "tflops": 685.76,
                    "efficiency": 1.0,
                    "time_ms": 1.603,
                },
                {
                    "size": 16384,
                    "tflops": 717.5,
                    "efficiency": 1.0463,
                    "time_ms": 12.259,
                },
                {
                    "size": 32768,
                    "tflops": 556.92,
                    "efficiency": 0.8121,
                    "time_ms": 126.353,
                },
                {
                    "size": 65536,
                    "tflops": 684.91,
                    "efficiency": 0.9988,
                    "time_ms": 821.938,
                },
            ],
        },
        "bf16_gemm_samples": [
            {
                "family": "kv_proj",
                "m": 256,
                "n": 512,
                "k": 2048,
                "tflops": 43.16,
                "efficiency": 0.0629,
                "time_ms": 0.012,
            },
            {
                "family": "kv_proj",
                "m": 1024,
                "n": 512,
                "k": 2048,
                "tflops": 174.25,
                "efficiency": 0.2541,
                "time_ms": 0.012,
            },
            {
                "family": "kv_proj",
                "m": 4096,
                "n": 512,
                "k": 2048,
                "tflops": 520.27,
                "efficiency": 0.7587,
                "time_ms": 0.017,
            },
            {
                "family": "kv_proj",
                "m": 8192,
                "n": 512,
                "k": 2048,
                "tflops": 577.2,
                "efficiency": 0.8417,
                "time_ms": 0.03,
            },
            {
                "family": "dense_ffn_up",
                "m": 256,
                "n": 6144,
                "k": 2048,
                "tflops": 405.99,
                "efficiency": 0.592,
                "time_ms": 0.016,
            },
            {
                "family": "dense_ffn_up",
                "m": 1024,
                "n": 6144,
                "k": 2048,
                "tflops": 650.23,
                "efficiency": 0.9482,
                "time_ms": 0.04,
            },
            {
                "family": "dense_ffn_up",
                "m": 4096,
                "n": 6144,
                "k": 2048,
                "tflops": 744.58,
                "efficiency": 1.0,
                "time_ms": 0.138,
            },
            {
                "family": "dense_ffn_up",
                "m": 8192,
                "n": 6144,
                "k": 2048,
                "tflops": 730.71,
                "efficiency": 1.0,
                "time_ms": 0.282,
            },
            {
                "family": "dense_ffn_down",
                "m": 256,
                "n": 2048,
                "k": 6144,
                "tflops": 333.5,
                "efficiency": 0.4863,
                "time_ms": 0.019,
            },
            {
                "family": "dense_ffn_down",
                "m": 1024,
                "n": 2048,
                "k": 6144,
                "tflops": 703.34,
                "efficiency": 1.0,
                "time_ms": 0.037,
            },
            {
                "family": "dense_ffn_down",
                "m": 4096,
                "n": 2048,
                "k": 6144,
                "tflops": 786.56,
                "efficiency": 1.0,
                "time_ms": 0.131,
            },
            {
                "family": "dense_ffn_down",
                "m": 8192,
                "n": 2048,
                "k": 6144,
                "tflops": 791.91,
                "efficiency": 1.0,
                "time_ms": 0.26,
            },
            {
                "family": "router",
                "m": 256,
                "n": 128,
                "k": 2048,
                "tflops": 11.16,
                "efficiency": 0.0163,
                "time_ms": 0.012,
            },
            {
                "family": "router",
                "m": 1024,
                "n": 128,
                "k": 2048,
                "tflops": 44.73,
                "efficiency": 0.0652,
                "time_ms": 0.012,
            },
            {
                "family": "router",
                "m": 4096,
                "n": 128,
                "k": 2048,
                "tflops": 174.97,
                "efficiency": 0.2552,
                "time_ms": 0.012,
            },
            {
                "family": "router",
                "m": 8192,
                "n": 128,
                "k": 2048,
                "tflops": 347.96,
                "efficiency": 0.5074,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_up",
                "m": 16,
                "n": 768,
                "k": 2048,
                "tflops": 4.19,
                "efficiency": 0.0061,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_up",
                "m": 64,
                "n": 768,
                "k": 2048,
                "tflops": 16.86,
                "efficiency": 0.0246,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_up",
                "m": 256,
                "n": 768,
                "k": 2048,
                "tflops": 66.85,
                "efficiency": 0.0975,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_up",
                "m": 1024,
                "n": 768,
                "k": 2048,
                "tflops": 260.52,
                "efficiency": 0.3799,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_down",
                "m": 16,
                "n": 2048,
                "k": 768,
                "tflops": 4.23,
                "efficiency": 0.0062,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_down",
                "m": 64,
                "n": 2048,
                "k": 768,
                "tflops": 16.97,
                "efficiency": 0.0247,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_down",
                "m": 256,
                "n": 2048,
                "k": 768,
                "tflops": 65.47,
                "efficiency": 0.0955,
                "time_ms": 0.012,
            },
            {
                "family": "expert_ffn_down",
                "m": 1024,
                "n": 2048,
                "k": 768,
                "tflops": 265.02,
                "efficiency": 0.3865,
                "time_ms": 0.012,
            },
        ],
        "intra_node_bw_curve": {
            "peak_bw_gbps": 405.7506,
            "k": 0.667563,
            "x0": 14.427853,
            "points": [
                {
                    "size_bytes": 1024,
                    "bandwidth_gbps": 1.2313,
                },
                {
                    "size_bytes": 4096,
                    "bandwidth_gbps": 9.7955,
                },
                {
                    "size_bytes": 16384,
                    "bandwidth_gbps": 15.0877,
                },
                {
                    "size_bytes": 65536,
                    "bandwidth_gbps": 41.5021,
                },
                {
                    "size_bytes": 262144,
                    "bandwidth_gbps": 134.8365,
                },
                {
                    "size_bytes": 1048576,
                    "bandwidth_gbps": 220.2469,
                },
                {
                    "size_bytes": 4194304,
                    "bandwidth_gbps": 249.001,
                },
                {
                    "size_bytes": 16777216,
                    "bandwidth_gbps": 314.6998,
                },
                {
                    "size_bytes": 67108864,
                    "bandwidth_gbps": 370.3936,
                },
                {
                    "size_bytes": 268435456,
                    "bandwidth_gbps": 386.4291,
                },
            ],
        },
        "inter_node_bw_curve": {
            "peak_bw_gbps": 49.2827,
            "k": 0.53211,
            "x0": 13.898973,
            "points": [
                {
                    "size_bytes": 1024,
                    "bandwidth_gbps": 2.4314,
                },
                {
                    "size_bytes": 4096,
                    "bandwidth_gbps": 2.8764,
                },
                {
                    "size_bytes": 16384,
                    "bandwidth_gbps": 4.8567,
                },
                {
                    "size_bytes": 65536,
                    "bandwidth_gbps": 3.3625,
                },
                {
                    "size_bytes": 262144,
                    "bandwidth_gbps": 5.5883,
                },
                {
                    "size_bytes": 1048576,
                    "bandwidth_gbps": 29.1101,
                },
                {
                    "size_bytes": 4194304,
                    "bandwidth_gbps": 41.729,
                },
                {
                    "size_bytes": 16777216,
                    "bandwidth_gbps": 42.0017,
                },
                {
                    "size_bytes": 67108864,
                    "bandwidth_gbps": 42.9788,
                },
                {
                    "size_bytes": 268435456,
                    "bandwidth_gbps": 46.936,
                },
            ],
        },
        "host_to_device_bw_curve": {
            "peak_bw_gbps": 53.3273,
            "k": 0.907032,
            "x0": 15.373908,
            "points": [
                {
                    "size_bytes": 1024,
                    "bandwidth_gbps": 0.0212,
                },
                {
                    "size_bytes": 4096,
                    "bandwidth_gbps": 0.0692,
                },
                {
                    "size_bytes": 16384,
                    "bandwidth_gbps": 0.2961,
                },
                {
                    "size_bytes": 65536,
                    "bandwidth_gbps": 1.1208,
                },
                {
                    "size_bytes": 262144,
                    "bandwidth_gbps": 4.2942,
                },
                {
                    "size_bytes": 1048576,
                    "bandwidth_gbps": 13.286,
                },
                {
                    "size_bytes": 4194304,
                    "bandwidth_gbps": 29.314,
                },
                {
                    "size_bytes": 16777216,
                    "bandwidth_gbps": 43.1797,
                },
                {
                    "size_bytes": 67108864,
                    "bandwidth_gbps": 48.9322,
                },
                {
                    "size_bytes": 268435456,
                    "bandwidth_gbps": 50.7879,
                },
            ],
        },
        "device_to_host_bw_curve": {
            "peak_bw_gbps": 52.7366,
            "k": 0.965761,
            "x0": 15.326047,
            "points": [
                {
                    "size_bytes": 1024,
                    "bandwidth_gbps": 0.0053,
                },
                {
                    "size_bytes": 4096,
                    "bandwidth_gbps": 0.077,
                },
                {
                    "size_bytes": 16384,
                    "bandwidth_gbps": 0.2997,
                },
                {
                    "size_bytes": 65536,
                    "bandwidth_gbps": 1.2109,
                },
                {
                    "size_bytes": 262144,
                    "bandwidth_gbps": 3.9837,
                },
                {
                    "size_bytes": 1048576,
                    "bandwidth_gbps": 13.2619,
                },
                {
                    "size_bytes": 4194304,
                    "bandwidth_gbps": 29.4511,
                },
                {
                    "size_bytes": 16777216,
                    "bandwidth_gbps": 43.5131,
                },
                {
                    "size_bytes": 67108864,
                    "bandwidth_gbps": 49.214,
                },
                {
                    "size_bytes": 268435456,
                    "bandwidth_gbps": 50.2253,
                },
            ],
        },
        "gpus_per_node": 8,
        "calibrated_at": "2026-03-12T16:27:22.190827",
        "pdcost_version": "1.0.0",
    },
}
