# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Behavioural tests for sharding stage1-v2 (split-param) checkpoint helpers.

Target production module::

    src/paddlefleet/trainer/unified_checkpoint/sharding_split_param_utils.py

Oracle strategy (no reference is generated by calling the code under test):

* ``reshape_params`` -- for a sharding rank that owns the flat-buffer slice
  ``[begin, end)`` of a parameter whose real data lives at flat offset
  ``index`` (``numel`` real elements) inside a ``padded_size`` slot, the
  expected local shard is the hand-sliced ``full_flat[begin-index : end-index]``
  followed by ``max(0, min(end, index+padded_size) - max(begin, index+numel))``
  trailing zeros contributed by the padding region this rank owns. Expected
  slices/values are written out by hand below.
* ``get_params_info`` -- expected keys are exactly the buffer views with
  ``end > begin`` (empty shards excluded), preserving buffer iteration order;
  slice/shape tuples are read straight from the (real) grad-view attributes.
* ``merge_splited_param`` (non-communicating branch only) -- a param absent
  from ``partial_tensor_list`` is reshaped to its recorded shape with content
  preserved; a ``numel == 1`` scalar (beta accumulators) is passed through
  untouched; the non-master path derives the static name via
  ``generate_base_static_name`` so that lookup must succeed.

Parameters are chosen to share shape but differ in content so a key/ownership
swap changes values while passing any shape-only check. The communicating
branch of ``merge_splited_param`` (``dist.stream.send``/``recv`` between ranks)
and the fleet-dependent public entries cannot be validated without a real
process group; those numerics are left unverified and skipped.

Runs on CPU. Requires an importable ``paddle`` + ``paddlefleet``; when either
is missing every test skips rather than passing vacuously.
"""

import unittest

try:
    import paddle

    from paddlefleet.trainer.unified_checkpoint.sharding_split_param_utils import (
        get_params_info,
        merge_splited_param,
        reshape_params,
    )
    from paddlefleet.trainer.unified_checkpoint.utils import (
        generate_base_static_name,
    )

    _IMPORT_ERROR = None
except ImportError as exc:  # only real missing-dependency, not logic errors
    paddle = None
    _IMPORT_ERROR = exc

_SKIP_REASON = (
    f"paddle/paddlefleet not importable in this environment: {_IMPORT_ERROR!r}"
)


class _GradView:
    """Minimal stand-in for a sharding param/grad view holding real data.

    Only carries the attributes ``get_params_info`` reads; ``_param`` is a real
    paddle tensor so ``shape`` and ``numel().item()`` come from paddle itself.
    """

    def __init__(self, param, begin, end, index, padded_size):
        self._param = param
        self._param_begin = begin
        self._param_end = end
        self._index = index
        self._padded_size = padded_size


class _CommBuffer:
    def __init__(self, view_map):
        self._sharding_param_grad_view = view_map


@unittest.skipIf(paddle is None, _SKIP_REASON)
class TestReshapeParams(unittest.TestCase):
    """reshape_params: local shard = hand-sliced flat data + owned padding zeros."""

    def _run(self, full_values, struct2static, slice_info, shape_info):
        state_dict = {
            "w/moment1_0": paddle.to_tensor(full_values, dtype="float32"),
        }
        reshape_params(state_dict, struct2static, shape_info, slice_info)
        return state_dict["w/moment1_0"].tolist()

    def test_full_real_region_plus_owned_padding(self):
        # numel=6, index=0, padded_size=8; rank owns [0,8): all 6 reals + 2 pad.
        out = self._run(
            [10.0, 11.0, 12.0, 13.0, 14.0, 15.0],
            {"w": "w_s"},
            {"w_s": (0, 8)},
            {"w_s": ([2, 3], 6, 0, 8)},
        )
        self.assertEqual(out, [10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 0.0, 0.0])

    def test_partial_interior_no_padding(self):
        # rank owns flat [2,5): reals only, no padding appended.
        out = self._run(
            [10.0, 11.0, 12.0, 13.0, 14.0, 15.0],
            {"w": "w_s"},
            {"w_s": (2, 5)},
            {"w_s": ([2, 3], 6, 0, 8)},
        )
        self.assertEqual(out, [12.0, 13.0, 14.0])

    def test_boundary_spans_real_and_padding(self):
        # rank owns flat [4,8): reals at 4,5 then padding slots 6,7 -> two zeros.
        out = self._run(
            [10.0, 11.0, 12.0, 13.0, 14.0, 15.0],
            {"w": "w_s"},
            {"w_s": (4, 8)},
            {"w_s": ([2, 3], 6, 0, 8)},
        )
        self.assertEqual(out, [14.0, 15.0, 0.0, 0.0])

    def test_nonzero_index_offset(self):
        # param starts at flat offset 10; rank owns [12,16): reals 12..15, no pad.
        out = self._run(
            [10.0, 11.0, 12.0, 13.0, 14.0, 15.0],
            {"w": "w_s"},
            {"w_s": (12, 16)},
            {"w_s": ([2, 3], 6, 10, 8)},
        )
        self.assertEqual(out, [12.0, 13.0, 14.0, 15.0])

    def test_scalar_is_passed_through_untouched(self):
        # numel == 1 accumulator must not be sliced/padded/zeroed.
        state_dict = {
            "w/beta1_pow_acc_0": paddle.to_tensor([0.81], dtype="float32")
        }
        reshape_params(state_dict, {"w": "w_s"}, {}, {})
        self.assertEqual(list(state_dict["w/beta1_pow_acc_0"].shape), [1])
        # 0.81 has no exact float32 representation, so .tolist() yields the
        # float32-rounded value; assert closeness rather than exact fp equality.
        self.assertAlmostEqual(
            state_dict["w/beta1_pow_acc_0"].tolist()[0], 0.81, places=6
        )

    def test_ownership_swap_changes_content_not_shape(self):
        # Two params, same shape, different content; swapping the owned slice
        # produces same-shape but different values -> a shape-only check misses it.
        struct2static = {"wa": "wa_s", "wb": "wb_s"}
        shape_info = {"wa_s": ([2, 3], 6, 0, 6), "wb_s": ([2, 3], 6, 0, 6)}

        def run(slice_info):
            sd = {
                "wa/moment1_0": paddle.to_tensor(
                    [20.0, 21.0, 22.0, 23.0, 24.0, 25.0], dtype="float32"
                ),
                "wb/moment1_0": paddle.to_tensor(
                    [30.0, 31.0, 32.0, 33.0, 34.0, 35.0], dtype="float32"
                ),
            }
            reshape_params(sd, struct2static, shape_info, slice_info)
            return (
                sd["wa/moment1_0"].tolist(),
                sd["wb/moment1_0"].tolist(),
            )

        correct = run({"wa_s": (0, 3), "wb_s": (3, 6)})
        self.assertEqual(correct, ([20.0, 21.0, 22.0], [33.0, 34.0, 35.0]))

        swapped = run({"wa_s": (3, 6), "wb_s": (0, 3)})
        self.assertEqual(swapped, ([23.0, 24.0, 25.0], [30.0, 31.0, 32.0]))

        # same shard length either way, but content diverges.
        self.assertEqual(
            [len(correct[0]), len(correct[1])],
            [len(swapped[0]), len(swapped[1])],
        )
        self.assertNotEqual(correct, swapped)


@unittest.skipIf(paddle is None, _SKIP_REASON)
class TestGetParamsInfo(unittest.TestCase):
    """get_params_info: keep only views with end > begin, read real attributes."""

    def test_empty_buffer_list(self):
        keys, slice_info, shape_info = get_params_info([])
        self.assertEqual(keys, [])
        self.assertEqual(slice_info, {})
        self.assertEqual(shape_info, {})

    def test_excludes_empty_shard_and_reads_real_values(self):
        views = {
            "a": _GradView(paddle.zeros([2, 3], dtype="float32"), 0, 6, 0, 8),
            "b": _GradView(  # end == begin -> this rank owns nothing, dropped
                paddle.zeros([2, 3], dtype="float32"), 6, 6, 0, 8
            ),
            "c": _GradView(paddle.zeros([4], dtype="float32"), 6, 10, 6, 4),
        }
        keys, slice_info, shape_info = get_params_info([_CommBuffer(views)])

        self.assertEqual(keys, ["a", "c"])  # order preserved, "b" filtered out
        self.assertNotIn("b", slice_info)
        self.assertNotIn("b", shape_info)
        self.assertEqual(slice_info, {"a": (0, 6), "c": (6, 10)})

        shape_a, numel_a, index_a, padded_a = shape_info["a"]
        self.assertEqual(list(shape_a), [2, 3])
        self.assertEqual(numel_a, 6)
        self.assertIsInstance(numel_a, int)
        self.assertEqual((index_a, padded_a), (0, 8))

        shape_c, numel_c, index_c, padded_c = shape_info["c"]
        self.assertEqual(list(shape_c), [4])
        self.assertEqual((numel_c, index_c, padded_c), (4, 6, 4))


@unittest.skipIf(paddle is None, _SKIP_REASON)
class TestMergeSplitedParam(unittest.TestCase):
    """merge_splited_param: non-communicating (no partial) branch behaviour."""

    def test_master_full_param_reshaped_and_preserved(self):
        state_dict = {"w": paddle.arange(6, dtype="float32")}
        result = merge_splited_param(
            state_dict,
            partial_tensor_list=[],
            param_shape_info={"w": ([2, 3], 6, 0, 8)},
            send_table={},
            recv_table={},
            is_master_weights=True,
        )
        self.assertEqual(list(result["w"].shape), [2, 3])
        self.assertEqual(
            result["w"].tolist(), [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]]
        )

    def test_scalar_accumulator_untouched(self):
        state_dict = {
            "beta1_pow_acc_0": paddle.to_tensor([0.81], dtype="float32")
        }
        result = merge_splited_param(
            state_dict,
            partial_tensor_list=[],
            param_shape_info={},
            send_table={},
            recv_table={},
            is_master_weights=True,
        )
        self.assertEqual(list(result["beta1_pow_acc_0"].shape), [1])
        # 0.81 has no exact float32 representation, so .tolist() yields the
        # float32-rounded value; assert closeness rather than exact fp equality.
        self.assertAlmostEqual(
            result["beta1_pow_acc_0"].tolist()[0], 0.81, places=6
        )

    def test_nonmaster_path_uses_generate_base_static_name(self):
        # Non-master keys resolve their static name via generate_base_static_name;
        # if that derivation were bypassed the param_shape_info lookup would fail.
        key = "embedding_0.w_0_moment1_0"
        self.assertEqual(
            generate_base_static_name(key), ("embedding_0.w_0", "moment1_0")
        )
        state_dict = {key: paddle.arange(6, dtype="float32")}
        result = merge_splited_param(
            state_dict,
            partial_tensor_list=[],
            param_shape_info={"embedding_0.w_0": ([3, 2], 6, 0, 6)},
            send_table={},
            recv_table={},
            is_master_weights=False,
        )
        self.assertEqual(list(result[key].shape), [3, 2])
        self.assertEqual(
            result[key].tolist(), [[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]]
        )

    def test_partial_merge_needs_real_process_group(self):
        # The partial-tensor branch drives dist.stream.send/recv between distinct
        # sharding ranks; its cross-rank concatenation cannot be validated in a
        # single CPU process. Left unverified here (needs a real process group).
        self.skipTest(
            "cross-rank send/recv merge unverifiable without a real process group"
        )


if __name__ == "__main__":
    unittest.main()
