pull_request_rules:
  - name: auto add to merge queue
    conditions:
      - check-success=Test
      - check-success=Test-release
      - or:
          - base=develop
          - base~=^release/
      - updated-at<24 hours ago
    actions:
      update:
