# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Behavior tests for ``paddlefleet.process_groups_config.ProcessGroupCollection``.

``ProcessGroupCollection`` is a small config container in the distributed layer.
Its two behaviours worth pinning down are validation and dispatch, not plain
attribute storage:

* ``__init__(**kwargs)`` only accepts keys that match declared dataclass fields
  (tp / pp / cp / ep / dp / cp_dp / expt_dp) and otherwise raises ``ValueError``
  whose message names the offending key.
* ``use_mpu_process_groups(required_pgs)`` validates the requested names against
  the field set (reporting exactly the unknown ones), then routes each requested
  name to a *specific* ``parallel_state`` group getter and stores the returned
  handle in the matching field. The interesting derived contract is the routing
  table itself -- in particular ``dp`` and ``cp_dp`` both call
  ``get_data_parallel_group`` but ``cp_dp`` must pass ``with_context_parallel=True``
  while ``dp`` must not, and every getter is called with ``check_initialized=False``.

The ``parallel_state`` group getters are non-code-under-test collaborators, so
they are replaced with distinguishable fakes that return a unique marker per
group (and, for the data-parallel getter, a marker that depends on the
``with_context_parallel`` flag). The code under test -- the validation branch
and the routing/dispatch logic -- is exercised for real. Expected values (the
per-field marker mapping, the exact invalid-name list, the passed kwargs) are
derived by hand from the contract above, never generated by the production code.

Because the production module imports ``paddle`` transitively at import time,
the whole suite is skipped with an honest reason when Paddle / paddlefleet is
unavailable on the host rather than reporting a hollow pass.
"""

import contextlib
import os
import sys
import unittest
import unittest.mock

# Make the in-tree ``src/paddlefleet`` importable when the package has not been
# pip-installed into the environment (repo_root/src is 4 levels up from here).
_REPO_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
_SRC = os.path.join(_REPO_ROOT, "src")
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

try:
    import paddle  # noqa: F401

    from paddlefleet import parallel_state
    from paddlefleet.process_groups_config import ProcessGroupCollection

    _IMPORT_ERROR = None
except ImportError as exc:  # paddle / paddlefleet not installed on this host
    parallel_state = None
    ProcessGroupCollection = None
    _IMPORT_ERROR = exc


# The routing contract, transcribed by hand from the module: field name -> the
# marker its designated getter must yield. ``dp`` and ``cp_dp`` share
# ``get_data_parallel_group`` but are disambiguated by ``with_context_parallel``.
_EXPECTED_MARKERS = {
    "tp": "MARK_TP",
    "pp": "MARK_PP",
    "cp": "MARK_CP",
    "ep": "MARK_EP",
    "dp": "MARK_DP",
    "cp_dp": "MARK_DP_WITH_CP",
    "expt_dp": "MARK_EXPT_DP",
}


@unittest.skipUnless(
    _IMPORT_ERROR is None,
    f"paddle/paddlefleet unavailable: {_IMPORT_ERROR}",
)
class TestProcessGroupCollection(unittest.TestCase):
    """Validation and getter-dispatch behaviour of ProcessGroupCollection."""

    def _patch_getters(self, stack):
        """Replace every ``parallel_state`` group getter with a fake.

        Each fake records the ``check_initialized`` value it was called with and
        returns a unique marker so the caller can prove which getter fed which
        field. The data-parallel fake additionally branches on
        ``with_context_parallel`` so ``dp`` vs ``cp_dp`` routing is observable.
        Returns the shared ``calls`` record.
        """
        calls = {}

        def make_simple(name, marker):
            def fake(check_initialized=True):
                calls[name] = {"check_initialized": check_initialized}
                return marker

            return fake

        def fake_dp(check_initialized=True, with_context_parallel=False):
            key = "cp_dp" if with_context_parallel else "dp"
            calls[key] = {
                "check_initialized": check_initialized,
                "with_context_parallel": with_context_parallel,
            }
            return (
                _EXPECTED_MARKERS["cp_dp"]
                if with_context_parallel
                else _EXPECTED_MARKERS["dp"]
            )

        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state,
                "get_tensor_model_parallel_group",
                make_simple("tp", _EXPECTED_MARKERS["tp"]),
            )
        )
        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state,
                "get_pipeline_model_parallel_group",
                make_simple("pp", _EXPECTED_MARKERS["pp"]),
            )
        )
        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state,
                "get_context_parallel_group",
                make_simple("cp", _EXPECTED_MARKERS["cp"]),
            )
        )
        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state,
                "get_expert_model_parallel_group",
                make_simple("ep", _EXPECTED_MARKERS["ep"]),
            )
        )
        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state,
                "get_expert_data_parallel_group",
                make_simple("expt_dp", _EXPECTED_MARKERS["expt_dp"]),
            )
        )
        stack.enter_context(
            unittest.mock.patch.object(
                parallel_state, "get_data_parallel_group", fake_dp
            )
        )
        return calls

    def test_init_rejects_unknown_key_and_names_it(self):
        """Unknown kwargs raise ValueError whose message identifies the key."""
        with self.assertRaises(ValueError) as ctx:
            ProcessGroupCollection(not_a_real_group=object())
        self.assertIn("not_a_real_group", str(ctx.exception))

    def test_init_validates_every_key_even_alongside_valid_ones(self):
        """Validation covers all keys, not just the first; a lone bad key trips it."""
        # ``tp`` is a legitimate field, ``bogus`` is not: the presence of a valid
        # key must not let the invalid one slip through.
        with self.assertRaises(ValueError) as ctx:
            ProcessGroupCollection(tp=object(), bogus=object())
        self.assertIn("bogus", str(ctx.exception))

    def test_use_mpu_reports_exactly_the_invalid_names(self):
        """Invalid request lists precisely the unknown names, in input order."""
        with self.assertRaises(ValueError) as ctx:
            ProcessGroupCollection.use_mpu_process_groups(
                required_pgs=["tp", "bogus1", "dp", "bogus2"]
            )
        msg = str(ctx.exception)
        # Hand-derived: filtering the request against the field set, preserving
        # order, yields exactly ['bogus1', 'bogus2'] -- valid names excluded.
        self.assertIn("['bogus1', 'bogus2']", msg)
        self.assertNotIn("'tp'", msg)
        self.assertNotIn("'dp'", msg)

    def test_use_mpu_routes_dp_and_cp_dp_by_context_flag(self):
        """dp and cp_dp share one getter but differ by with_context_parallel.

        This is the load-bearing dispatch contract: swapping the two fields, or
        dropping ``with_context_parallel=True`` for cp_dp, would be caught here.
        """
        with contextlib.ExitStack() as stack:
            calls = self._patch_getters(stack)
            pgs = ProcessGroupCollection.use_mpu_process_groups(
                required_pgs=["dp", "cp_dp"]
            )

        self.assertEqual(pgs.dp, _EXPECTED_MARKERS["dp"])
        self.assertEqual(pgs.cp_dp, _EXPECTED_MARKERS["cp_dp"])
        # The plain-dp call must not request context parallel; cp_dp must.
        self.assertFalse(calls["dp"]["with_context_parallel"])
        self.assertTrue(calls["cp_dp"]["with_context_parallel"])
        # Both go through the uninitialized-safe path.
        self.assertFalse(calls["dp"]["check_initialized"])
        self.assertFalse(calls["cp_dp"]["check_initialized"])

    def test_use_mpu_subset_routes_only_requested_fields(self):
        """A named subset populates exactly those fields from the right getters."""
        requested = ["tp", "ep", "expt_dp"]
        with contextlib.ExitStack() as stack:
            calls = self._patch_getters(stack)
            pgs = ProcessGroupCollection.use_mpu_process_groups(
                required_pgs=requested
            )

        for name in requested:
            self.assertEqual(getattr(pgs, name), _EXPECTED_MARKERS[name])
            self.assertFalse(calls[name]["check_initialized"])
        # Unrequested fields were never assigned by init_dict.
        for name in ("pp", "cp", "dp", "cp_dp"):
            self.assertFalse(hasattr(pgs, name))

    def test_use_mpu_none_pulls_all_fields_from_matching_getters(self):
        """required_pgs=None populates every declared field via its own getter."""
        with contextlib.ExitStack() as stack:
            calls = self._patch_getters(stack)
            pgs = ProcessGroupCollection.use_mpu_process_groups(
                required_pgs=None
            )

        for name, marker in _EXPECTED_MARKERS.items():
            self.assertEqual(
                getattr(pgs, name),
                marker,
                msg=f"field {name} was fed by the wrong getter",
            )
            self.assertFalse(calls[name]["check_initialized"])


if __name__ == "__main__":
    unittest.main()
