# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Structural / branch-level tests for paddlefleet.models.gpt.gpt_model.

Scope and honesty statement
---------------------------
These tests exercise the *pure control flow* of GPTModel: the pipeline layout
produced by ``get_layer_desc_list`` (including the tie / MTP / magic-send /
experimental branches), the sequential-layer bookkeeping helpers, the shared
layer prefix resolution, the weight-only-MTP parameter filter and its
offload/reload place gating, plus the module-level ``is_vision_merge_key``
guard and the ``GPTSublayersSpec`` dataclass contract.

They do NOT construct a real ``PipelineLayer`` (that needs Fleet / distributed
init and a device), so they do NOT validate real pipeline-parallel execution,
weight tying at runtime, actual GPU<->CPU parameter migration, or any collective
behaviour. Those require the single-card / multi-card environments. The methods
under test are called on genuine ``GPTModel`` instances built with
``__new__`` (so the real methods run against real ``LayerDesc`` /
``SharedLayerDesc`` objects); only genuinely device/topology-bound collaborators
(``state_dict``, ``get_stage_from_index``) are supplied with controlled,
input-dependent behaviour.

Expected pipeline layouts below are hand-derived from the branch order in
``GPTModel.get_layer_desc_list`` and are not generated by calling the code under
test.
"""

import types
import unittest

try:  # Only ImportError is treated as "environment lacks the dependency".
    import paddle
    from paddle.distributed.fleet.meta_parallel import (
        LayerDesc,
        SharedLayerDesc,
    )

    from paddlefleet.models.gpt import gpt_model

    _IMPORT_ERROR = None
except ImportError as exc:  # pragma: no cover - depends on runtime env
    paddle = None
    LayerDesc = None
    SharedLayerDesc = None
    gpt_model = None
    _IMPORT_ERROR = exc

_SKIP_REASON = (
    "paddle / paddlefleet.models.gpt is not importable in this environment "
    f"({_IMPORT_ERROR!r}); GPTModel structural tests were NOT executed."
)


if gpt_model is not None:

    class _Dummy(paddle.nn.Layer):
        """Minimal real nn.Layer used as a LayerDesc payload.

        ``LayerDesc`` / ``SharedLayerDesc`` only *store* the class (they do not
        instantiate it at build time), so a single trivial layer type is enough
        to observe placement; the pipeline position is pinned by ``name_prefix``
        and the shared-vs-plain classification below.
        """

        def __init__(self, *args, **kwargs):
            super().__init__()

        def forward(self, *args, **kwargs):  # pragma: no cover - never run
            del args, kwargs

    class _Place:
        def __init__(self, is_gpu):
            self._is_gpu = is_gpu

        def is_gpu_place(self):
            return self._is_gpu

    class _Handle:
        """Stands in for the pinned-CPU / GPU buffer returned by a param."""

        def __init__(self):
            self.shared_to = None

        def _share_buffer_to(self, other):
            self.shared_to = other

    class _Param:
        """Faithful stub of a Parameter for the weight-only offload path.

        ``pin_memory`` / ``cuda`` each return a distinct handle and record it so
        the test can assert (a) which params were selected and (b) that the
        produced handle was shared back onto the original param, matching the
        real ``cpu_param._share_buffer_to(param)`` contract.
        """

        def __init__(self, weight_only, is_gpu):
            self.is_weight_only_mtp = weight_only
            self.place = _Place(is_gpu)
            self.pinned_handle = None
            self.cuda_handle = None

        def pin_memory(self):
            self.pinned_handle = _Handle()
            return self.pinned_handle

        def cuda(self):
            self.cuda_handle = _Handle()
            return self.cuda_handle


def _make_config(**overrides):
    values = {
        "model_type": "",
        "enable_mtp_magic_send": False,
        "gpt_model_use_experimental_version": False,
        "num_nextn_predict_layers": 0,
        "mtp_shared_last_layer": False,
        "multimax_modules": None,
        "separate_mtp_headloss": False,
    }
    values.update(overrides)
    return types.SimpleNamespace(**values)


def _make_spec(**overrides):
    values = {
        "embedding": _Dummy,
        "head_empty_layers": [_Dummy],
        "mhc_expand": None,
        "transformer_layers": [_Dummy, _Dummy],
        "mhc_contract": None,
        "tail_empty_layers": [_Dummy],
        "mtp": [],
        "output_block_attn_res": None,
        "layer_norm": _Dummy,
        "lm_head": _Dummy,
        "mtp_lm_head": None,
        "mtp_loss": None,
    }
    values.update(overrides)
    return gpt_model.GPTSublayersSpec(**values)


def _bare_model(config):
    """A real GPTModel whose PipelineLayer.__init__ has been skipped.

    Only ``self.config`` and the plain-python bookkeeping attributes are set,
    which is all the methods under test read. No distributed / device state.
    """
    model = gpt_model.GPTModel.__new__(gpt_model.GPTModel)
    model.config = config
    return model


def _prefixes(layers):
    return [entry["name_prefix"] for entry in layers]


def _descs(layers):
    return [entry["layer"] for entry in layers]


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestIsVisionMergeKey(unittest.TestCase):
    """Guards the vision_merge state-dict routing rule (gpt_model.py:55-78)."""

    def test_non_vision_merge_key_returns_false(self):
        self.assertFalse(
            gpt_model.is_vision_merge_key("model.layers.0.self_attn.weight")
        )
        self.assertFalse(gpt_model.is_vision_merge_key("model.lm_head.weight"))

    def test_vision_model_key_returns_true(self):
        self.assertTrue(
            gpt_model.is_vision_merge_key(
                "vision_merge.vision_model.encoder.layers.0.weight"
            )
        )
        # Exactly the vision_model prefix (no submodule) still routes as vision.
        self.assertTrue(
            gpt_model.is_vision_merge_key("vision_merge.vision_model.")
        )

    def test_param_directly_on_wrapper_is_rejected_loudly(self):
        # A key under vision_merge.* but not vision_merge.vision_model.* would be
        # silently dropped from every checkpoint, so the guard must raise (a
        # ValueError, not an assert that -O would strip).
        with self.assertRaises(ValueError):
            gpt_model.is_vision_merge_key("vision_merge.projector.weight")

    def test_bare_vision_merge_prefix_is_rejected(self):
        with self.assertRaises(ValueError):
            gpt_model.is_vision_merge_key("vision_merge.vision_modelX.weight")


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestGPTSublayersSpec(unittest.TestCase):
    """The dataclass carrying the LayerSpecs for every GPT sublayer slot."""

    _FIELD_NAMES = {
        "embedding",
        "head_empty_layers",
        "mhc_expand",
        "transformer_layers",
        "mhc_contract",
        "tail_empty_layers",
        "mtp",
        "output_block_attn_res",
        "layer_norm",
        "lm_head",
        "mtp_lm_head",
        "mtp_loss",
    }

    def test_all_fields_default_to_none(self):
        spec = gpt_model.GPTSublayersSpec()
        for name in self._FIELD_NAMES:
            self.assertIsNone(
                getattr(spec, name), msg=f"{name} should default to None"
            )

    def test_field_set_is_exactly_the_documented_twelve(self):
        import dataclasses

        actual = {
            f.name for f in dataclasses.fields(gpt_model.GPTSublayersSpec)
        }
        self.assertEqual(actual, self._FIELD_NAMES)

    def test_keyword_construction_assigns_each_slot(self):
        markers = {name: object() for name in self._FIELD_NAMES}
        spec = gpt_model.GPTSublayersSpec(**markers)
        for name, marker in markers.items():
            self.assertIs(getattr(spec, name), marker)


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestGetLayerDescList(unittest.TestCase):
    """Pipeline layout branches of GPTModel.get_layer_desc_list.

    Expected ``name_prefix`` sequences are hand-derived from the branch order in
    gpt_model.py:302-484 and the shared-vs-plain classification pins the tie /
    magic-send / MTP branches.
    """

    def test_plain_model_layout(self):
        model = _bare_model(_make_config())
        layers = model.get_layer_desc_list(
            _make_spec(), tie_word_embeddings=False
        )

        self.assertEqual(
            _prefixes(layers),
            [
                "model",  # plain LayerDesc embedding
                "model.layers.0",  # head_empty
                "model.layers.1",  # transformer 0
                "model.layers.2",  # transformer 1
                "model",  # layer_norm (before tail, non-experimental)
                "model.layers.3",  # tail_empty
                "model.lm_head",  # plain lm_head (no tie, no mtp_lm_head)
            ],
        )
        # No SharedLayerDesc anywhere on the plain path.
        for entry in _descs(layers):
            self.assertNotIsInstance(entry, SharedLayerDesc)
        self.assertIsInstance(layers[0]["layer"], LayerDesc)

    def test_qwen_experimental_mtp_layout(self):
        model = _bare_model(
            _make_config(
                model_type="qwen3_vl",
                gpt_model_use_experimental_version=True,
                num_nextn_predict_layers=1,
            )
        )
        spec = _make_spec(
            tail_empty_layers=[],
            mtp=[_Dummy],
            mtp_lm_head=_Dummy,
            mtp_loss=_Dummy,
        )

        layers = model.get_layer_desc_list(spec, tie_word_embeddings=True)

        self.assertEqual(
            _prefixes(layers),
            [
                "model.language_model",  # tied embedding (SharedLayerDesc)
                "model.language_model.layers.0",  # head_empty
                "model.language_model.layers.1",  # transformer 0
                "model.language_model.layers.2",  # transformer 1
                "model.language_model.layers.3",  # mtp layer
                "model.language_model.shared_mtp_lm_head",  # mtp_lm_head (shared)
                "model.language_model.mtp_loss",  # mtp_loss
                "model.language_model",  # layer_norm (after MTP: experimental)
                "model.language_model.shared_head",  # lm_head (shared)
            ],
        )
        shared_indices = {0, 5, 8}
        for idx, entry in enumerate(_descs(layers)):
            if idx in shared_indices:
                self.assertIsInstance(entry, SharedLayerDesc)
                self.assertEqual(entry.layer_name, "embed")
            else:
                self.assertNotIsInstance(entry, SharedLayerDesc)

    def test_magic_send_uses_mtp_embed_shared_embedding(self):
        model = _bare_model(_make_config(enable_mtp_magic_send=True))
        spec = _make_spec(
            head_empty_layers=[],
            transformer_layers=[_Dummy],
            tail_empty_layers=[],
        )

        layers = model.get_layer_desc_list(spec, tie_word_embeddings=False)

        self.assertEqual(
            _prefixes(layers),
            ["model", "model.layers.0", "model", "model.lm_head"],
        )
        # magic-send tags the embedding with the distinct "mtp_embed" key, not
        # the "embed" key used by the tie_word_embeddings path.
        self.assertIsInstance(layers[0]["layer"], SharedLayerDesc)
        self.assertEqual(layers[0]["layer"].layer_name, "mtp_embed")
        self.assertNotIsInstance(layers[-1]["layer"], SharedLayerDesc)


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestSequentialLayerBookkeeping(unittest.TestCase):
    """add_sequential_layer / get_sequential_layers / _name_prefixes."""

    def test_append_order_and_index_to_prefix_mapping(self):
        model = _bare_model(_make_config())
        layers = []
        first = object()
        second = object()
        third = object()
        model.add_sequential_layer(layers, first, "a.prefix")
        model.add_sequential_layer(layers, second, "b.prefix")
        model.add_sequential_layer(layers, third, "c.prefix")

        self.assertEqual(
            layers,
            [
                {"layer": first, "name_prefix": "a.prefix"},
                {"layer": second, "name_prefix": "b.prefix"},
                {"layer": third, "name_prefix": "c.prefix"},
            ],
        )

        model._sequential_layers = layers
        # Preserves object identity and order, not just count.
        seq = model.get_sequential_layers()
        self.assertEqual(len(seq), 3)
        self.assertIs(seq[0], first)
        self.assertIs(seq[1], second)
        self.assertIs(seq[2], third)
        self.assertEqual(
            model.get_sequential_name_prefixes(),
            {"0": "a.prefix", "1": "b.prefix", "2": "c.prefix"},
        )


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestGetShardlayerPrefix(unittest.TestCase):
    """SharedLayerDesc -> single-card prefix resolution (gpt_model.py:609-644).

    ``get_stage_from_index`` is a PipelineLayer collaborator that needs real
    topology; it is supplied here with a controlled index->stage map so the
    shared-layer lookup and the stage-membership gate run for real.
    """

    def _model_with_shared_embed(self, stage_of_index, stage_id):
        model = _bare_model(_make_config())
        shared = SharedLayerDesc(
            "embed", _Dummy, shared_weight_attr="embedding_weight"
        )
        plain = LayerDesc(_Dummy)
        model.layers = [plain, shared]
        model._sequential_layers = [
            {"layer": plain, "name_prefix": "model.embed_pre"},
            {"layer": shared, "name_prefix": "model.embed"},
        ]
        model._stage_id = stage_id
        model.get_stage_from_index = lambda idx: stage_of_index[idx]
        return model

    def test_returns_prefix_when_shared_layer_on_current_stage(self):
        model = self._model_with_shared_embed(
            stage_of_index={0: 0, 1: 0}, stage_id=0
        )
        self.assertEqual(
            model.get_shardlayer_prefix(["shared_layers", "embed", "weight"]),
            "model.embed",
        )

    def test_unknown_shared_name_fails_assertion(self):
        model = self._model_with_shared_embed(
            stage_of_index={0: 0, 1: 0}, stage_id=0
        )
        with self.assertRaises(AssertionError):
            model.get_shardlayer_prefix(
                ["shared_layers", "not_a_shared_layer", "weight"]
            )

    def test_shared_layer_on_other_stage_raises_value_error(self):
        # Name is valid, but the shared layer lives on stage 1 while we are
        # stage 0, so no local prefix exists -> ValueError.
        model = self._model_with_shared_embed(
            stage_of_index={0: 1, 1: 1}, stage_id=0
        )
        with self.assertRaises(ValueError):
            model.get_shardlayer_prefix(["shared_layers", "embed", "weight"])


@unittest.skipUnless(gpt_model is not None, _SKIP_REASON)
class TestWeightOnlyParamOffloadReload(unittest.TestCase):
    """_get_weight_only_params + offload/reload place gating.

    ``state_dict`` is a heavy PipelineLayer collaborator; it is replaced with a
    controlled mapping so the flag filter and the place-based offload/reload
    gates (gpt_model.py:253-300) run against distinguishable params. Real
    GPU<->CPU migration is not exercised.
    """

    def _model_with_params(self):
        gpu_wo = _Param(weight_only=True, is_gpu=True)
        cpu_wo = _Param(weight_only=True, is_gpu=False)
        gpu_plain = _Param(weight_only=False, is_gpu=True)
        model = _bare_model(_make_config())
        model.state_dict = lambda: {
            "a.weight": gpu_wo,
            "b.weight": cpu_wo,
            "c.weight": gpu_plain,
        }
        return model, gpu_wo, cpu_wo, gpu_plain

    def test_filter_selects_only_weight_only_params_in_order(self):
        model, gpu_wo, cpu_wo, gpu_plain = self._model_with_params()
        selected = model._get_weight_only_params()
        # gpu_plain excluded despite being on GPU; order follows state_dict.
        self.assertEqual(len(selected), 2)
        self.assertIs(selected[0], gpu_wo)
        self.assertIs(selected[1], cpu_wo)

    def test_offload_pins_only_gpu_weight_only_params(self):
        model, gpu_wo, cpu_wo, gpu_plain = self._model_with_params()
        model.offload_weight_only_params()

        # GPU weight-only param: pinned and the pinned handle shared back to it.
        self.assertIsNotNone(gpu_wo.pinned_handle)
        self.assertIs(gpu_wo.pinned_handle.shared_to, gpu_wo)
        # Already on CPU -> not pinned again.
        self.assertIsNone(cpu_wo.pinned_handle)
        # Not weight-only -> never selected.
        self.assertIsNone(gpu_plain.pinned_handle)
        # Offload must not call cuda() on anything.
        self.assertIsNone(gpu_wo.cuda_handle)
        self.assertIsNone(cpu_wo.cuda_handle)

    def test_reload_moves_only_cpu_weight_only_params(self):
        model, gpu_wo, cpu_wo, gpu_plain = self._model_with_params()
        model.reload_weight_only_params()

        # CPU weight-only param: moved to GPU and shared back to it.
        self.assertIsNotNone(cpu_wo.cuda_handle)
        self.assertIs(cpu_wo.cuda_handle.shared_to, cpu_wo)
        # Already on GPU -> not reloaded.
        self.assertIsNone(gpu_wo.cuda_handle)
        # Not weight-only -> never selected.
        self.assertIsNone(gpu_plain.cuda_handle)
        # Reload must not call pin_memory() on anything.
        self.assertIsNone(gpu_wo.pinned_handle)
        self.assertIsNone(cpu_wo.pinned_handle)


if __name__ == "__main__":
    unittest.main()
