# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CPU-observable unit tests for the HySparse block-sparse DSA backend
(:mod:`paddlefleet.cudnn_ops.block_sparse_mqa_dsa`).

Scope. ``block_sparse_mqa_dsa`` bridges HySparse *block* selection onto the
token-level FlashMLA-sparse-fwd + cuDNN-DSA-bwd kernel that lives in the
separate module ``paddlefleet.fusions.mqa_sparse_attn``. The GPU/cuDNN kernel
numerics (forward attention values, dQ/dKV/dSink) are SM100+-only and are NOT
asserted here -- they require the real device and belong to a single-card
numeric run. What IS pure integer/layout logic on the CPU side, and is what
these tests pin down:

* ``_expand_blocks_to_token_indices`` -- the doc-relative block id -> absolute
  key-column expansion, with the ``>= eos`` causal tail masking and ``-1``
  padding-block masking folded in. Every expected column list below is
  hand-derived by enumerating ``bos + blk*block_B + offset`` and applying the
  two masking rules; nothing is generated by the function under test.
* The ``kv_lora_rank > 512`` argument-validation guard in
  ``block_sparse_mqa_attention_dsa``.
* The value-padding re-lay (``[value | zeros | rope]`` for ``kv_lora_rank <
  512``), the ``sm_scale`` default, and the output slice-back -- verified by
  replacing the genuine (non-under-test) ``mqa_sparse_attn`` kernel collaborator
  with a marker and checking the exact tensors the wrapper hands it and the
  exact tensor it returns.

Everything runs on CPU. When Paddle is not importable the whole suite skips
with an honest reason; the kernel-collaborator tests additionally skip when
``paddlefleet.fusions.mqa_sparse_attn`` cannot be imported. No production code
is modified.
"""

import unittest
from unittest import mock

import numpy as np

try:
    import paddle

    from paddlefleet.cudnn_ops.block_sparse_mqa_dsa import (
        _expand_blocks_to_token_indices,
        block_sparse_mqa_attention_dsa,
    )

    _HAS_PADDLE = True
except ImportError:
    _HAS_PADDLE = False

try:
    import paddlefleet.fusions.mqa_sparse_attn as _mqa_mod

    _HAS_MQA = True
except ImportError:
    _HAS_MQA = False


@unittest.skipUnless(_HAS_PADDLE, "requires an importable Paddle build")
class TestExpandBlocksToTokenIndices(unittest.TestCase):
    """Pure integer index-expansion math (CPU; no GPU/cuDNN involved).

    ``_expand_blocks_to_token_indices(indices, valid_range, block_B)`` turns
    each doc-relative block id ``blk`` for query row ``i`` into ``block_B``
    absolute key columns ``bos_i + blk*block_B + [0..block_B)``; a column is set
    to ``-1`` iff (a) the block id is ``< 0`` (padding), or (b) the column is
    ``>= eos_i``. Blocks are laid out contiguously, so the last axis has width
    ``topk * block_B`` in block-major, offset-minor order.
    """

    def setUp(self):
        orig = paddle.device.get_device()
        self.addCleanup(paddle.set_device, orig)
        paddle.set_device("cpu")

    def _expand(self, indices, valid_range, block_B):
        idx = paddle.to_tensor(np.array(indices, dtype=np.int32))
        vr = paddle.to_tensor(np.array(valid_range, dtype=np.int32))
        return _expand_blocks_to_token_indices(idx, vr, block_B)

    def test_two_packed_queries_tail_and_padding_masking(self):
        """B=1,S=2,topk=2,block_B=4. Row 0 (bos=0,eos=6) selects blocks 0,1;
        row 1 (bos=2,eos=5) selects block 0 and a -1 padding block.

        Hand derivation (block-major, offset-minor):
          row0 blk0: 0+0*4+[0,1,2,3]=[0,1,2,3]  (all <6)         -> [0,1,2,3]
          row0 blk1: 0+1*4+[0,1,2,3]=[4,5,6,7]  (6,7 >= eos=6)   -> [4,5,-1,-1]
          row1 blk0: 2+0*4+[0,1,2,3]=[2,3,4,5]  (5 >= eos=5)     -> [2,3,4,-1]
          row1 blk-1: padding block                              -> [-1,-1,-1,-1]
        """
        out = self._expand(
            indices=[[[0, 1], [0, -1]]],
            valid_range=[[[0, 6], [2, 5]]],
            block_B=4,
        )
        expected = [
            [
                [0, 1, 2, 3, 4, 5, -1, -1],
                [2, 3, 4, -1, -1, -1, -1, -1],
            ]
        ]
        self.assertEqual(out.tolist(), expected)
        self.assertEqual(out.dtype, paddle.int32)
        self.assertEqual(list(out.shape), [1, 2, 2 * 4])
        # Pure index construction must not carry an autograd edge.
        self.assertTrue(out.stop_gradient)

    def test_block_size_is_consumed(self):
        """Same block ids, block_B=2: start = bos + blk*2, width topk*2.
          bos=0,eos=3,blocks=[0,1]:
            blk0: [0,1]  (all <3)                 -> [0,1]
            blk1: [2,3]  (3 >= eos=3)             -> [2,-1]
        A hardcoded block_B (e.g. 64) or a wrong multiplier would not produce
        this.
        """
        out = self._expand(
            indices=[[[0, 1]]],
            valid_range=[[[0, 3]]],
            block_B=2,
        )
        self.assertEqual(out.tolist(), [[[0, 1, 2, -1]]])
        self.assertEqual(list(out.shape), [1, 1, 2 * 2])

    def test_nonzero_bos_and_fully_clipped_block(self):
        """Packed doc with bos=10,eos=12, blocks=[0,1], block_B=4:
            blk0: 10+[0,1,2,3]=[10,11,12,13] (12,13 >= 12) -> [10,11,-1,-1]
            blk1: 14+[0,1,2,3]=[14,15,16,17] (all >= 12)   -> [-1,-1,-1,-1]
        Confirms bos offsetting and that an entire block past eos becomes -1.
        """
        out = self._expand(
            indices=[[[0, 1]]],
            valid_range=[[[10, 12]]],
            block_B=4,
        )
        self.assertEqual(out.tolist(), [[[10, 11, -1, -1, -1, -1, -1, -1]]])

    def test_all_selected_columns_in_range_are_verbatim(self):
        """When no column reaches eos, every expanded column is the exact
        absolute index (no spurious masking). bos=5,eos=100,block=3,block_B=4:
            5+3*4+[0,1,2,3]=[17,18,19,20], all < 100 -> [17,18,19,20].
        """
        out = self._expand(
            indices=[[[3]]],
            valid_range=[[[5, 100]]],
            block_B=4,
        )
        self.assertEqual(out.tolist(), [[[17, 18, 19, 20]]])


@unittest.skipUnless(_HAS_PADDLE, "requires an importable Paddle build")
class TestArgValidationGuard(unittest.TestCase):
    """The ``kv_lora_rank <= 512`` guard is reached on CPU before any kernel
    call, so it is asserted with the real production entry point (no mock)."""

    def setUp(self):
        orig = paddle.device.get_device()
        self.addCleanup(paddle.set_device, orig)
        paddle.set_device("cpu")

    @unittest.skipUnless(
        _HAS_MQA, "requires importable paddlefleet.fusions.mqa_sparse_attn"
    )
    def test_kv_lora_rank_above_512_raises_value_error(self):
        """kv_lora_rank=576 -> pad_v = 512-576 = -64 < 0 -> ValueError, raised
        after the pure index expansion and before mqa_sparse_attn is invoked."""
        b, s, h, dk = 1, 1, 1, 600
        query = paddle.zeros([b, s, h, dk], dtype="float32")
        shared_key_sq = paddle.zeros([b, s, dk], dtype="float32")
        shared_block_indices = paddle.zeros([b, s, 1], dtype="int32")
        valid_range = paddle.to_tensor(np.array([[[0, 1]]], dtype=np.int32))
        with self.assertRaises(ValueError) as cm:
            block_sparse_mqa_attention_dsa(
                query,
                shared_key_sq,
                shared_block_indices,
                valid_range,
                kv_lora_rank=576,
            )
        self.assertIn("kv_lora_rank", str(cm.exception))


@unittest.skipUnless(_HAS_PADDLE, "requires an importable Paddle build")
@unittest.skipUnless(
    _HAS_MQA, "requires importable paddlefleet.fusions.mqa_sparse_attn"
)
class TestWrapperCpuOrchestration(unittest.TestCase):
    """CPU-observable pre/post-processing around the DSA kernel.

    ``mqa_sparse_attn`` is the FlashMLA-sparse-fwd + cuDNN-DSA-bwd kernel entry
    -- a genuine collaborator that lives in another module and is NOT the code
    under test (its GPU numerics need SM100+). We replace it with a marker that
    records the exact tensors it receives and returns a position-encoded tensor,
    so we can pin the wrapper's real value-pad re-lay, sm_scale default and
    output slice-back without a GPU. The kernel's own math is out of scope here.
    """

    def setUp(self):
        orig = paddle.device.get_device()
        self.addCleanup(paddle.set_device, orig)
        paddle.set_device("cpu")

    def test_value_pad_relay_and_output_sliceback(self):
        """kv_lora_rank=3 < 512 => pad_v=509 value-pad path. Dk=5 (value=3,
        rope=2), so the kernel must receive
        query_p = [value(3) | zeros(509) | rope(2)] (width 514) and eff_d_v=512;
        the returned [.,.,H,512] is sliced back to leading 3 per head.

        token_indices expected (block_B=4, topk=2), same derivation as the
        pure-expansion suite:
          row0 (bos=0,eos=6, blk 0,1): [0,1,2,3, 4,5,-1,-1]
          row1 (bos=2,eos=5, blk 0,-1): [2,3,4,-1, -1,-1,-1,-1]
        """
        b, s, h, dk, klr = 1, 2, 2, 5, 3
        query = paddle.arange(b * s * h * dk, dtype="float32").reshape(
            [b, s, h, dk]
        )
        shared_key_sq = (
            paddle.arange(b * s * dk, dtype="float32") + 100.0
        ).reshape([b, s, dk])
        shared_block_indices = paddle.to_tensor(
            np.array([[[0, 1], [0, -1]]], dtype=np.int32)
        )
        valid_range = paddle.to_tensor(
            np.array([[[0, 6], [2, 5]]], dtype=np.int32)
        )

        captured = {}

        def fake_kernel(q_p, k_p, tok_idx, scale, d_v, sink):
            captured.update(
                q_p=q_p,
                k_p=k_p,
                tok_idx=tok_idx,
                scale=scale,
                d_v=d_v,
                sink=sink,
            )
            # value dim index c is recoverable in the last axis.
            col = paddle.arange(512, dtype="float32").reshape([1, 1, 1, 512])
            return paddle.broadcast_to(col, [b, s, h, 512])

        with mock.patch.object(
            _mqa_mod, "mqa_sparse_attn", side_effect=fake_kernel
        ):
            out, lse = block_sparse_mqa_attention_dsa(
                query,
                shared_key_sq,
                shared_block_indices,
                valid_range,
                sm_scale=0.125,
                block_B=4,
                kv_lora_rank=klr,
                attn_sink=None,
            )

        q_p = captured["q_p"]
        k_p = captured["k_p"]
        self.assertEqual(list(q_p.shape), [b, s, h, 514])
        self.assertEqual(list(k_p.shape), [b, s, 514])
        # [value | zeros | rope] re-lay, verified region by region.
        np.testing.assert_array_equal(
            q_p[..., :klr].numpy(), query[..., :klr].numpy()
        )
        np.testing.assert_array_equal(
            q_p[..., klr:512].numpy(),
            np.zeros([b, s, h, 512 - klr], dtype=np.float32),
        )
        np.testing.assert_array_equal(
            q_p[..., 512:].numpy(), query[..., klr:].numpy()
        )
        np.testing.assert_array_equal(
            k_p[..., :klr].numpy(), shared_key_sq[..., :klr].numpy()
        )
        np.testing.assert_array_equal(
            k_p[..., klr:512].numpy(),
            np.zeros([b, s, 512 - klr], dtype=np.float32),
        )
        np.testing.assert_array_equal(
            k_p[..., 512:].numpy(), shared_key_sq[..., klr:].numpy()
        )
        # eff_d_v is forced to the kernel's fixed 512, sm_scale forwarded as
        # a python float, sinkless request forwarded as None.
        self.assertEqual(captured["d_v"], 512)
        self.assertIsInstance(captured["scale"], float)
        self.assertEqual(captured["scale"], 0.125)
        self.assertIsNone(captured["sink"])
        # token_indices == hand-derived expansion.
        self.assertEqual(
            captured["tok_idx"].tolist(),
            [
                [
                    [0, 1, 2, 3, 4, 5, -1, -1],
                    [2, 3, 4, -1, -1, -1, -1, -1],
                ]
            ],
        )
        # Output slice keeps the LEADING kv_lora_rank per head: each head's
        # 512 marker columns (value==c) collapse to [0,1,2].
        self.assertIsNone(lse)
        self.assertEqual(list(out.shape), [b, s, h * klr])
        expected_out = np.array(
            [[[0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2]]], dtype=np.float32
        )
        np.testing.assert_array_equal(out.numpy(), expected_out)

    def test_no_pad_path_passes_inputs_through_and_defaults_scale(self):
        """kv_lora_rank=512 => pad_v=0: inputs handed to the kernel unchanged,
        eff_d_v=512, default sm_scale = Dk**-0.5, and the kernel output returned
        verbatim (no slice-back). Also cross-checks the bos-offset expansion.

        token_indices (block_B=4, topk=1):
          row0 (bos=0,eos=3, blk0): 0+[0,1,2,3]=[0,1,2,3] (3>=3) -> [0,1,2,-1]
          row1 (bos=4,eos=10,blk1): 8+[0,1,2,3]=[8,9,10,11] (10,11>=10)
                                                            -> [8,9,-1,-1]
        """
        b, s, h, dk = 1, 2, 1, 512
        query = paddle.zeros([b, s, h, dk], dtype="float32")
        shared_key_sq = paddle.zeros([b, s, dk], dtype="float32")
        shared_block_indices = paddle.to_tensor(
            np.array([[[0], [1]]], dtype=np.int32)
        )
        valid_range = paddle.to_tensor(
            np.array([[[0, 3], [4, 10]]], dtype=np.int32)
        )

        captured = {}
        marker = paddle.arange(b * s * h * dk, dtype="float32").reshape(
            [b, s, h * dk]
        )

        def fake_kernel(q_p, k_p, tok_idx, scale, d_v, sink):
            captured.update(
                q_p=q_p, k_p=k_p, tok_idx=tok_idx, scale=scale, d_v=d_v
            )
            return marker

        with mock.patch.object(
            _mqa_mod, "mqa_sparse_attn", side_effect=fake_kernel
        ):
            out, lse = block_sparse_mqa_attention_dsa(
                query,
                shared_key_sq,
                shared_block_indices,
                valid_range,
                block_B=4,
                kv_lora_rank=512,
            )

        self.assertIs(captured["q_p"], query)
        self.assertIs(captured["k_p"], shared_key_sq)
        self.assertEqual(captured["d_v"], 512)
        self.assertAlmostEqual(captured["scale"], dk**-0.5, places=9)
        self.assertEqual(
            captured["tok_idx"].tolist(),
            [[[0, 1, 2, -1], [8, 9, -1, -1]]],
        )
        self.assertIs(out, marker)
        self.assertIsNone(lse)


if __name__ == "__main__":
    unittest.main()
