# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Behavior tests for ``paddlefleet.transformer.enums``.

These tests verify the concrete, CPU-observable contract of the transformer
enums: each member's exact name/value mapping, that the mappings are complete
(no missing/extra members, no accidental aliasing), that value/name lookups
resolve to the right identity, and that the deprecated ``ModelType`` property
raises. All expected mappings below are HAND-TRANSCRIBED from the production
source; they are never generated by iterating the enum under test.
"""

import enum as _std_enum
import unittest

# ``paddlefleet`` imports ``paddle`` at import time. The enums submodule itself
# only depends on the stdlib ``enum`` today, but importing it goes through the
# ``paddlefleet`` package, which may pull in ``paddle``. Guard defensively so a
# missing ``paddle`` in a CPU-only environment produces an honest skip rather
# than a fake pass.
try:
    from paddlefleet.transformer import enums as pf_enums

    _IMPORT_ERROR = None
except ImportError as exc:  # pragma: no cover - environment dependent
    pf_enums = None
    _IMPORT_ERROR = exc


_SKIP_REASON = (
    "paddlefleet.transformer.enums is not importable in this environment "
    f"(likely missing paddle): {_IMPORT_ERROR!r}"
)


# ---------------------------------------------------------------------------
# Hand-derived expected mappings, transcribed by reading enums.py directly.
# Each dict maps member name -> integer value exactly as written in source.
# ---------------------------------------------------------------------------
EXPECTED_MODEL_TYPE = {"encoder_or_decoder": 1}
EXPECTED_LAYER_TYPE = {
    "embedding": 1,
    "loss": 2,
    "encoder": 3,
    "decoder": 4,
    "mtp": 5,
}
EXPECTED_ATTN_TYPE = {"self_attn": 1, "cross_attn": 2}
EXPECTED_ATTN_MASK_TYPE = {
    "padding": 1,
    "causal": 2,
    "no_mask": 3,
    "padding_causal": 4,
    "arbitrary": 5,
    "causal_bottom_right": 6,
}
EXPECTED_ATTN_BACKEND = {
    "flash": 1,
    "fused": 2,
    "unfused": 3,
    "local": 4,
    "auto": 5,
}


@unittest.skipUnless(pf_enums is not None, _SKIP_REASON)
class EnumMappingContractTest(unittest.TestCase):
    """Full name->value contract for every enum, plus lookup identity."""

    def _assert_enum_matches(self, enum_cls, expected):
        # Build the ACTUAL mapping by iterating the enum under test; the
        # EXPECTED mapping is the hand-written literal above. Comparing the two
        # catches missing members, extra members, renamed members and wrong
        # values in one shot.
        actual = {member.name: member.value for member in enum_cls}
        self.assertEqual(actual, expected)

        # No accidental aliasing: distinct values means len(enum) == #names.
        # (enum collapses duplicate values into aliases, which iteration hides,
        # so assert against the canonical member list explicitly.)
        self.assertEqual(len(list(enum_cls)), len(expected))
        self.assertEqual(len(enum_cls.__members__), len(expected))

        # Every member must be a real instance of its enum, and value/name
        # lookups must round-trip to the SAME member object (identity).
        for name, value in expected.items():
            member = enum_cls[name]
            self.assertIsInstance(member, enum_cls)
            self.assertEqual(member.name, name)
            self.assertEqual(member.value, value)
            self.assertIs(enum_cls(value), member)
            self.assertIs(enum_cls[name], member)

    def test_model_type_contract(self):
        self._assert_enum_matches(pf_enums.ModelType, EXPECTED_MODEL_TYPE)

    def test_layer_type_contract(self):
        self._assert_enum_matches(pf_enums.LayerType, EXPECTED_LAYER_TYPE)

    def test_attn_type_contract(self):
        self._assert_enum_matches(pf_enums.AttnType, EXPECTED_ATTN_TYPE)

    def test_attn_mask_type_contract(self):
        self._assert_enum_matches(
            pf_enums.AttnMaskType, EXPECTED_ATTN_MASK_TYPE
        )

    def test_attn_backend_contract(self):
        self._assert_enum_matches(pf_enums.AttnBackend, EXPECTED_ATTN_BACKEND)


@unittest.skipUnless(pf_enums is not None, _SKIP_REASON)
class EnumIdentityAndEqualityTest(unittest.TestCase):
    """Members are singletons; distinct members never compare equal."""

    def test_members_are_std_enum(self):
        # These are plain stdlib enums, not IntEnum: a member must NOT equal its
        # own raw integer value (an IntEnum regression would silently break
        # this and let value comparisons leak in).
        self.assertIsInstance(pf_enums.LayerType.embedding, _std_enum.Enum)
        self.assertNotEqual(pf_enums.LayerType.embedding, 1)
        self.assertNotEqual(pf_enums.AttnBackend.flash, 1)

    def test_member_identity_and_distinctness(self):
        self.assertIs(pf_enums.LayerType.encoder, pf_enums.LayerType["encoder"])
        self.assertIs(pf_enums.LayerType.encoder, pf_enums.LayerType(3))
        self.assertNotEqual(
            pf_enums.LayerType.embedding, pf_enums.LayerType.decoder
        )
        # Cross-enum values collide numerically (both == 1) but must never be
        # equal as members; a shared/merged enum would break this.
        self.assertNotEqual(
            pf_enums.LayerType.embedding, pf_enums.AttnType.self_attn
        )
        self.assertNotEqual(
            pf_enums.ModelType.encoder_or_decoder, pf_enums.LayerType.embedding
        )

    def test_invalid_lookups_raise(self):
        # Value/name lookups outside the declared set must raise, proving the
        # enum is closed over exactly the transcribed members.
        with self.assertRaises(ValueError):
            pf_enums.LayerType(0)
        with self.assertRaises(ValueError):
            pf_enums.AttnMaskType(7)
        with self.assertRaises(KeyError):
            _ = pf_enums.AttnBackend["does_not_exist"]


@unittest.skipUnless(pf_enums is not None, _SKIP_REASON)
class ModelTypeDeprecationTest(unittest.TestCase):
    """The deprecated ``encoder_and_decoder`` property must raise on access."""

    def test_deprecated_property_raises_on_member_access(self):
        # Accessed via a member instance, the property getter runs and raises.
        with self.assertRaises(ValueError) as ctx:
            _ = pf_enums.ModelType.encoder_or_decoder.encoder_and_decoder
        self.assertIn("deprecated", str(ctx.exception))

    def test_deprecated_property_is_not_a_member(self):
        # The property must NOT have been turned into an enum member; the enum
        # still contains exactly one member.
        self.assertNotIn("encoder_and_decoder", pf_enums.ModelType.__members__)
        self.assertEqual(len(list(pf_enums.ModelType)), 1)


if __name__ == "__main__":
    unittest.main()
