# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CPU-only behavior tests for the device-independent logic that
``paddlefleet.pipeline_parallel.pp_utils.four_directions_p2p_communication``
relies on.

This file deliberately targets logic that the base sibling test does NOT
cover, to avoid duplication:

1. The dtype wire-protocol codec (``paddle_2_number`` / ``number_2_dtype`` in
   the ``pp_utils.utils`` collaborator). ``SendRecvMeta._send_dims_shape_dtype``
   encodes ``tensor.dtype`` to an integer with ``paddle_2_number`` before it is
   put on the wire, and ``_p2p_helper`` reconstructs the receive buffers with
   ``number_2_dtype``. If the two tables are not exact inverses, a tensor sent
   as one dtype would be received as another, so the encode/decode round-trip
   is a real correctness contract of the four-direction p2p path.

2. The XPU comm-group hooks (``_xpu_comm_group_start`` / ``_xpu_comm_group_end``)
   that ``_p2p_helper`` brackets its non-sync send/recv with. On a build that is
   NOT compiled with XPU these must be inert no-ops that never flip the
   ``_xpu_comm_group_started`` module flag.

The distributed send/recv, meta exchange over process groups and the
four-direction ``_p2p_helper`` scheduling all require a real pipeline process
group and are intentionally NOT covered here: faking ``world_size`` and mocking
collectives would only prove local orchestration, not cross-rank semantics.

Expected dtype codes are taken directly from the documented on-wire protocol
(float16=0, float32=1, float64=2, int32=3, int64=4, bfloat16=5, bool=6) and are
hand-written below, NOT produced by calling the production codec, so the test
and the code under test do not share a single source of truth.
"""

import unittest

try:
    import paddle

    from paddlefleet.pipeline_parallel.pp_utils import (
        four_directions_p2p_communication as p2p,
        utils as pp_utils,
    )

    _IMPORT_ERROR = None
except (ImportError, ModuleNotFoundError) as exc:  # honest dependency probe
    paddle = None
    p2p = None
    pp_utils = None
    _IMPORT_ERROR = exc

_HAS_DEPS = _IMPORT_ERROR is None
_SKIP_REASON = (
    f"paddle / paddlefleet not importable on this CPU host: {_IMPORT_ERROR!r}"
)


@unittest.skipUnless(_HAS_DEPS, _SKIP_REASON)
class TestDtypeWireProtocolCodec(unittest.TestCase):
    """`paddle_2_number` / `number_2_dtype` encode/decode the p2p metadata.

    Independent, hand-written protocol table (dtype -> integer code -> dtype
    name). Neither direction is generated by calling the other production
    helper, so a broken table cannot pass by self-agreement.
    """

    def _protocol_table(self):
        # (paddle dtype, wire integer, dtype name) fixed by the p2p protocol.
        return [
            (paddle.float16, 0, "float16"),
            (paddle.float32, 1, "float32"),
            (paddle.float64, 2, "float64"),
            (paddle.int32, 3, "int32"),
            (paddle.int64, 4, "int64"),
            (paddle.bfloat16, 5, "bfloat16"),
            (paddle.bool, 6, "bool"),
        ]

    def test_encode_matches_protocol_codes(self):
        for dtype, code, _name in self._protocol_table():
            self.assertEqual(pp_utils.paddle_2_number(dtype), code)

    def test_decode_matches_protocol_names(self):
        for _dtype, code, name in self._protocol_table():
            self.assertEqual(pp_utils.number_2_dtype(code), name)

    def test_roundtrip_recovers_original_dtype(self):
        # Sender: dtype -> code. Receiver: code -> dtype name -> paddle dtype.
        # The reconstructed dtype the receiver would hand to paddle.empty must
        # equal what the sender started with; otherwise buffers mismatch.
        for dtype, _code, name in self._protocol_table():
            code = pp_utils.paddle_2_number(dtype)
            recovered_name = pp_utils.number_2_dtype(code)
            self.assertEqual(recovered_name, name)
            self.assertEqual(getattr(paddle, recovered_name), dtype)

    def test_codes_are_distinct_bijection(self):
        codes = [code for _d, code, _n in self._protocol_table()]
        names = [name for _d, _c, name in self._protocol_table()]
        self.assertEqual(len(set(codes)), len(codes))
        self.assertEqual(len(set(names)), len(names))

    def test_encode_rejects_unknown_dtype(self):
        # A non-dtype key is not in the mapping; the explicit assert must fire
        # rather than silently returning a bogus code onto the wire.
        with self.assertRaises(AssertionError):
            pp_utils.paddle_2_number("float32")

    def test_decode_rejects_unknown_code(self):
        # 7 is one past the last valid protocol code (bool == 6).
        with self.assertRaises(AssertionError):
            pp_utils.number_2_dtype(7)


@unittest.skipUnless(_HAS_DEPS, _SKIP_REASON)
class TestXpuCommGroupNoOpOnNonXpuBuild(unittest.TestCase):
    """`_xpu_comm_group_start` / `_xpu_comm_group_end` are inert without XPU.

    ``_p2p_helper`` brackets its comm ops with these hooks; on a non-XPU build
    they must return immediately and never toggle ``_xpu_comm_group_started``.
    Runs the real functions with no mocking of the code under test.
    """

    def setUp(self):
        if paddle.is_compiled_with_xpu():
            self.skipTest(
                "paddle build IS compiled with XPU; the no-op branch under "
                "test is only reachable on a non-XPU build"
            )
        # Guard against leaking flag mutation to other tests in this process.
        orig = p2p._xpu_comm_group_started
        self.addCleanup(lambda: setattr(p2p, "_xpu_comm_group_started", orig))

    def test_start_is_noop_and_flag_stays_false(self):
        p2p._xpu_comm_group_started = False
        # Real call; the ``not is_compiled_with_xpu()`` guard returns early and
        # must NOT set the started flag on this build.
        self.assertIsNone(p2p._xpu_comm_group_start())
        self.assertFalse(p2p._xpu_comm_group_started)

    def test_end_is_noop_and_leaves_flag_untouched(self):
        p2p._xpu_comm_group_started = False
        self.assertIsNone(p2p._xpu_comm_group_end())
        self.assertFalse(p2p._xpu_comm_group_started)

    def test_end_does_not_clear_a_preexisting_true_flag(self):
        # On a non-XPU build _xpu_comm_group_end returns before the reset, so a
        # flag that was already True is left as-is (the reset is XPU-only).
        p2p._xpu_comm_group_started = True
        self.assertIsNone(p2p._xpu_comm_group_end())
        self.assertTrue(p2p._xpu_comm_group_started)


if __name__ == "__main__":
    unittest.main()
