name: Manual build wheel

on:
  workflow_dispatch:
    inputs:
      job-name:
        required: true
        default: 'publish-wheel'
        type: choice
        options:
          - publish-wheel
      commit:
        required: true
        type: string


permissions: read-all


env:
  PR_ID: '0'
  COMMIT_ID: ${{ github.sha }}
  BRANCH: ${{ github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  clone:
    name: Clone PaddleFleet
    uses: ./.github/workflows/_clone.yml
    with:
      clone_dir: manual
      ref: ${{ inputs.commit }}
      commit: ${{ inputs.commit }}
      submodules: 'false'

  publish-wheel:
    name: Manual build fleet (${{ matrix.cuda.CUDA_VERSION }}, python${{ matrix.python_version }})
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFleet'
    runs-on:
      group: GZ_BD-CPU
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.12"]
        cuda:
          - {CUDA_VERSION: CUDA13.0, IMAGE_TAG: cuda13.0-cudnn9.13-trt10.13-gcc11, bos_CUDA: cu130}
    env:
      TASK: PaddleFleet-manual
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      CCACHE_DIR: "/home/data/shared/.ccache/l1" # L1 cache on machine shared dir
      CCACHE_SECONDARY_STORAGE: "file:///home/data/cfs/.ccache/l2" # L2 cache on cfs
      CCACHE_MAXSIZE: 50G
      CCACHE_LIMIT_MULTIPLE: 0.8
      UV_HTTP_TIMEOUT: 600
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        id: check-skip
        run: |
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle_manylinux_devel:${{ matrix.cuda.IMAGE_TAG }}"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v "/home/data/shared:/home/data/shared" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e CCACHE_DIR \
            -e CCACHE_SECONDARY_STORAGE \
            -e CCACHE_MAXSIZE \
            -e CCACHE_LIMIT_MULTIPLE \
            -e UV_HTTP_TIMEOUT \
            -e PR_ID \
            -e COMMIT_ID \
            -e BRANCH \
            -e AK=paddle \
            -e SK=paddle \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image

      - name: Install PaddleFleet
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          source /root/proxy
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${PR_ID}/${{ inputs.commit }}/PaddleFleet.tar.gz --no-check-certificate
          echo "Extracting PaddleFleet.tar.gz"
          tar -xf PaddleFleet.tar.gz --strip-components=1
          rm PaddleFleet.tar.gz
          git config --global --add safe.directory /workspace
          sed -i "s#packages/nightly/cu129#packages/nightly/${{ matrix.cuda.bos_CUDA }}#g" pyproject.toml
          cat pyproject.toml
          mkdir -p /root/.cache/pip
          pip cache dir
          pip install --upgrade pip
          pip install uv
          python -m pip install bce-python-sdk==0.8.74
          '

      - name: Build wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          export UV_PYTHON=${{ matrix.python_version }}
          source /root/proxy
          git submodule update --init --recursive
          export IS_NVIDIA=True
          uv build --wheel -v
          # uv build --wheel --package paddlefleet-ops -v
          '

      - name: Upload wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          for whl in paddlefleet-*.whl; do
            echo "Uploading ${whl}"
            python ../bos/BosClient.py ${whl} paddle-github-action/PaddleFleet/manual/${{ inputs.commit }}/
            echo "https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${{ inputs.commit }}/${whl}"
          done
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
          exit 0
