name: Manual build wheel with ops

on:
  workflow_dispatch:
    inputs:
      job-name:
        required: true
        default: 'publish-wheel'
        type: choice
        options:
          - publish-wheel
      commit:
        required: true
        type: string
      cuda:
        required: false
        type: choice
        default: 'ALL'
        options:
          - ALL
          - "CUDA12.6"
          - "CUDA12.9"
          - "CUDA13.0"
      python:
        required: false
        type: choice
        default: 'ALL'
        options:
          - ALL
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      paddle:
        required: false
        type: choice
        default: 'release'
        options:
          - "develop"
          - "release"


permissions: read-all


env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  clone:
    name: Clone PaddleFleet
    uses: ./.github/workflows/_clone.yml
    with:
      clone_dir: manual
      ref: ${{ inputs.commit }}
      commit: ${{ inputs.commit }}

  publish-wheel:
    name: Manual build fleet with ops (${{ matrix.cuda.CUDA_VERSION }}, python${{ matrix.python_version }})
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFleet' && inputs.paddle == 'release'
    runs-on:
      group: GZ_BD-CPU
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
        cuda:
          - {CUDA_VERSION: CUDA12.6, IMAGE_TAG: cuda12.6-cudnn9.5-trt10.5-gcc11, bos_CUDA: cu126, CUDA_ARCH_LIST: "8.0;9.0"}
          - {CUDA_VERSION: CUDA12.9, IMAGE_TAG: cuda12.9-cudnn9.9-trt10.5-gcc11, bos_CUDA: cu129, CUDA_ARCH_LIST: "8.0;9.0;10.0;10.3"}
          - {CUDA_VERSION: CUDA13.0, IMAGE_TAG: cuda13.0-cudnn9.13-trt10.13-gcc11, bos_CUDA: cu130, CUDA_ARCH_LIST: "8.0;9.0;10.0;10.3"}
    env:
      TASK: PaddleFleet-ops-${{ matrix.cuda.CUDA_VERSION }}-${{ matrix.python_version }}
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      UV_HTTP_TIMEOUT: 600
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        id: check-skip
        run: |
          if ! [[ ( "${{ inputs.python }}" == "ALL" || "${{ inputs.python }}" == "${{ matrix.python_version }}" ) && ( "${{ inputs.cuda }}" == "ALL" || "${{ inputs.cuda }}" == "${{ matrix.cuda.CUDA_VERSION }}" ) ]]; then
            echo "no_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle_manylinux_devel:${{ matrix.cuda.IMAGE_TAG }}"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e UV_HTTP_TIMEOUT \
            -e PR_ID \
            -e PADDLE_CUDA_ARCH_LIST="${{ matrix.cuda.CUDA_ARCH_LIST }}" \
            -e COMMIT_ID \
            -e BRANCH \
            -e AK=paddle \
            -e SK=paddle \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image

      - name: Install PaddleFleet
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          source /root/proxy
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${PR_ID}/${{ inputs.commit }}/PaddleFleet.tar.gz --no-check-certificate
          echo "Extracting PaddleFleet.tar.gz"
          tar -xf PaddleFleet.tar.gz --strip-components=1
          rm PaddleFleet.tar.gz
          git config --global --add safe.directory /workspace
          git submodule foreach --recursive "git config --global --add safe.directory \$toplevel/\$sm_path"
          sed -i "s#packages/nightly/cu129#packages/nightly/${{ matrix.cuda.bos_CUDA }}#g" pyproject.toml
          cat pyproject.toml
          mkdir -p /root/.cache/pip
          pip cache dir
          pip install --upgrade pip
          pip install uv
          python -m pip install bce-python-sdk==0.8.74
          '

      - name: Build wheel
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          export UV_PYTHON=${{ matrix.python_version }}
          source /root/proxy
          git submodule update --init --recursive
          export IS_NVIDIA=True
          uv build --wheel -v
          pip install dist/paddlefleet-*.whl --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/${{ matrix.cuda.bos_CUDA }}/ --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/${{ matrix.cuda.bos_CUDA }}/
          pip install packaging "setuptools>=66.1.0" wheel
          if [[ ${{ matrix.cuda.bos_CUDA }} == "cu129" ]]; then
            pip install "paddle-nvidia-nvshmem-cu12>=3.3.9,<3.5" --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          elif [[ ${{ matrix.cuda.bos_CUDA }} == "cu130" ]]; then
            pip install "paddle-nvidia-nvshmem-cu13>=3.3.9,<3.5" --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu130/
          else
            pip install "nvidia-nvshmem-cu12>=3.3.9,<3.5"
          fi
          uv build --wheel --package paddlefleet-ops --out-dir dist --no-build-isolation -v
          '

      - name: Upload wheel
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          for whl in paddlefleet_ops-*.whl; do
            echo "Uploading ${whl}"
            python ../bos/BosClient.py ${whl} paddle-github-action/PaddleFleet/manual/${{ inputs.commit }}/${{ matrix.cuda.bos_CUDA }}/paddle-release
            echo "https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${{ inputs.commit }}/${{ matrix.cuda.bos_CUDA }}/paddle-release/${whl}"
          done
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
          exit 0

  publish-wheel-paddle-dev:
    name: Manual build fleet on paddle-dev with ops (${{ matrix.cuda.CUDA_VERSION }}, python${{ matrix.python_version }})
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFleet' && inputs.paddle == 'develop'
    runs-on:
      group: GZ_BD-CPU
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
        cuda:
          - {CUDA_VERSION: CUDA12.6, IMAGE_TAG: cuda12.6-cudnn9.5-trt10.5-gcc11, bos_CUDA: cu126, CUDA_ARCH_LIST: "8.0;9.0"}
          - {CUDA_VERSION: CUDA12.9, IMAGE_TAG: cuda12.9-cudnn9.9-trt10.5-gcc11, bos_CUDA: cu129, CUDA_ARCH_LIST: "8.0;9.0;10.0;10.3"}
          - {CUDA_VERSION: CUDA13.0, IMAGE_TAG: cuda13.0-cudnn9.13-trt10.13-gcc11, bos_CUDA: cu130, CUDA_ARCH_LIST: "8.0;9.0;10.0;10.3"}
    env:
      TASK: PaddleFleet-ops-${{ matrix.cuda.CUDA_VERSION }}-${{ matrix.python_version }}
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      UV_HTTP_TIMEOUT: 600
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        id: check-skip
        run: |
          if ! [[ ( "${{ inputs.python }}" == "ALL" || "${{ inputs.python }}" == "${{ matrix.python_version }}" ) && ( "${{ inputs.cuda }}" == "ALL" || "${{ inputs.cuda }}" == "${{ matrix.cuda.CUDA_VERSION }}" ) ]]; then
            echo "no_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle_manylinux_devel:${{ matrix.cuda.IMAGE_TAG }}"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e UV_HTTP_TIMEOUT \
            -e PR_ID \
            -e PADDLE_CUDA_ARCH_LIST="${{ matrix.cuda.CUDA_ARCH_LIST }}" \
            -e COMMIT_ID \
            -e BRANCH \
            -e AK=paddle \
            -e SK=paddle \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image

      - name: Install PaddleFleet
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          source /root/proxy
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${PR_ID}/${{ inputs.commit }}/PaddleFleet.tar.gz --no-check-certificate
          echo "Extracting PaddleFleet.tar.gz"
          tar -xf PaddleFleet.tar.gz --strip-components=1
          rm PaddleFleet.tar.gz
          git config --global --add safe.directory /workspace
          git submodule foreach --recursive "git config --global --add safe.directory \$toplevel/\$sm_path"
          sed -i "s#packages/nightly/cu129#packages/nightly/${{ matrix.cuda.bos_CUDA }}#g" pyproject.toml
          cat pyproject.toml
          mkdir -p /root/.cache/pip
          pip cache dir
          pip install --upgrade pip
          pip install uv
          python -m pip install bce-python-sdk==0.8.74
          '

      - name: Build wheel
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          export UV_PYTHON=${{ matrix.python_version }}
          source /root/proxy
          git submodule update --init --recursive
          export IS_NVIDIA=True
          python -m pip install --pre paddlepaddle-gpu -i https://www.paddlepaddle.org.cn/packages/nightly/${{ matrix.cuda.bos_CUDA }}/
          pip install packaging "setuptools>=66.1.0" wheel
          if [[ ${{ matrix.cuda.bos_CUDA }} == "cu129" ]]; then
            pip install "paddle-nvidia-nvshmem-cu12>=3.3.9,<3.5" --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          elif [[ ${{ matrix.cuda.bos_CUDA }} == "cu130" ]]; then
            pip install "paddle-nvidia-nvshmem-cu13>=3.3.9,<3.5" --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu130/
          else
            pip install "nvidia-nvshmem-cu12>=3.3.9,<3.5"
          fi
          uv build --wheel --package paddlefleet-ops --out-dir dist --no-build-isolation -v
          '

      - name: Upload wheel
        if: steps.check-skip.outputs.no_build != 'true'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          for whl in paddlefleet_ops-*.whl; do
            echo "Uploading ${whl}"
            python ../bos/BosClient.py ${whl} paddle-github-action/PaddleFleet/manual/${{ inputs.commit }}/${{ matrix.cuda.bos_CUDA }}/paddle-develop
            echo "https://paddle-github-action.bj.bcebos.com/PaddleFleet/manual/${{ inputs.commit }}/${{ matrix.cuda.bos_CUDA }}/paddle-develop/${whl}"
          done
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
          exit 0
