name: Publish wheel nightly

on:
  push:
    branches:
      - 'release/**'
      - 'develop'
    tags:
      - 'v*'


permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-all-${{ github.sha }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  clone:
    name: Clone PaddleFleet
    uses: ./.github/workflows/_clone.yml
    with:
      clone_dir: $BRANCH
      ref: ${{ github.event.pull_request.base.ref }}
      submodule: "false"

  publish-wheel:
    name: Publish wheel nightly
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFleet'
    runs-on:
      group: GZ_BD-CPU
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.12"]
        cuda:
          - {CUDA_VERSION: CUDA13.0, IMAGE_TAG: cuda13.0-cudnn9.13-trt10.13-gcc11, bos_CUDA: cu130, CUDA_ARCH_LIST: "8.0;9.0;10.0;10.3"}
    env:
      TASK: PaddleFleet-nightly
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      CCACHE_DIR: "/home/data/shared/.ccache/l1" # L1 cache on machine shared dir
      CCACHE_SECONDARY_STORAGE: "file:///home/data/cfs/.ccache/l2" # L2 cache on cfs
      CCACHE_MAXSIZE: 50G
      CCACHE_LIMIT_MULTIPLE: 0.8
      UV_HTTP_TIMEOUT: 600
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        run: |
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle_manylinux_devel:${{ matrix.cuda.IMAGE_TAG }}"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v "/home/data/shared:/home/data/shared" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e CCACHE_DIR \
            -e CCACHE_SECONDARY_STORAGE \
            -e CCACHE_MAXSIZE \
            -e CCACHE_LIMIT_MULTIPLE \
            -e UV_HTTP_TIMEOUT \
            -e PADDLE_CUDA_ARCH_LIST="${{ matrix.cuda.CUDA_ARCH_LIST }}" \
            -e PR_ID \
            -e COMMIT_ID \
            -e BRANCH \
            -e AK=${{ secrets.BOS_CREDENTIAL_AK }} \
            -e SK=${{ secrets.BOS_CREDENTIAL_SK }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image

      - name: Install PaddleFleet
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          source /root/proxy
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleFleet/${BRANCH}/${PR_ID}/${COMMIT_ID}/PaddleFleet.tar.gz --no-check-certificate
          echo "Extracting PaddleFleet.tar.gz"
          tar -xf PaddleFleet.tar.gz --strip-components=1
          rm PaddleFleet.tar.gz
          git config --global --add safe.directory /workspace
          sed -i "s#packages/nightly/cu129#packages/nightly/${{ matrix.cuda.bos_CUDA }}#g" pyproject.toml
          cat pyproject.toml
          mkdir -p /root/.cache/pip
          pip cache dir
          pip install --upgrade pip
          pip install uv
          python -m pip install bce-python-sdk==0.8.74
          '

      - name: Build wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          export UV_PYTHON=${{ matrix.python_version }}
          source /root/proxy
          uv cache clean paddlepaddle-gpu
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            VERSION="${TAG_NAME#v}"
            export PADDLEFLEET_VERSION=$VERSION
          fi
          export IS_NVIDIA=True
          uv build --wheel --package paddlefleet --out-dir dist --clear -v
          '

      - name: Upload wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export LD_LIBRARY_PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/lib/:${LD_LIBRARY_PATH}
          export PATH=/opt/_internal/cpython-${{ matrix.python_version }}.0/bin/:${PATH}
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          PY_VERSION="${{ matrix.python_version }}"
          PY_VERSION_SHORT="${PY_VERSION//./}"
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/nightly/cu126/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/nightly/cu129/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/nightly/cu130/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/nightly/cu132/paddlefleet
            export AK=paddle
            export SK=paddle
            python ../bos/BosClient.py paddlefleet-*.whl paddle-github-action/PaddleFleet/${BRANCH}/${COMMIT_ID}
            mv paddlefleet-*.whl paddlefleet-0.0.0-py3-none-linux_x86_64.whl
            python ../bos/BosClient.py paddlefleet-0.0.0-py3-none-linux_x86_64.whl paddle-github-action/PaddleFleet/${BRANCH}/latest
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/stable/cu126/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/stable/cu129/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/stable/cu130/paddlefleet
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/stable/cu132/paddlefleet
          fi
          curl https://www.paddlepaddle.org.cn/inner/whl/update/path/new
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}

  publish-wheel-arm:
    name: Publish arm wheel nightly (${{ matrix.cuda.CUDA_VERSION }}, python${{ matrix.python_version }})
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFleet'
    runs-on:
      group: npu-arm
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.12"]
        cuda:
          - {CUDA_VERSION: CUDA13.0, bos_CUDA: cu130}
    env:
      TASK: PaddleFleet-nightly-arm-${{ matrix.cuda.CUDA_VERSION }}
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      CCACHE_DIR: "/home/data/shared/.ccache/l1" # L1 cache on machine shared dir
      CCACHE_SECONDARY_STORAGE: "file:///home/data/cfs/.ccache/l2" # L2 cache on cfs
      CCACHE_MAXSIZE: 50G
      CCACHE_LIMIT_MULTIPLE: 0.8
      UV_HTTP_TIMEOUT: 600
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        run: |
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:cuda130-dev-arm-py312"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v "/home/data/shared:/home/data/shared" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e CCACHE_DIR \
            -e CCACHE_SECONDARY_STORAGE \
            -e CCACHE_MAXSIZE \
            -e CCACHE_LIMIT_MULTIPLE \
            -e UV_HTTP_TIMEOUT \
            -e PR_ID \
            -e COMMIT_ID \
            -e BRANCH \
            --shm-size 128G \
            --ulimit core=-1 \
            --cap-add SYS_ADMIN \
            --privileged=true \
            -v /ssd1:/ssd1 \
            -v /ssd2:/ssd2 \
            -v /ssd3:/ssd3 \
            -e AK=${{ secrets.BOS_CREDENTIAL_AK }} \
            -e SK=${{ secrets.BOS_CREDENTIAL_SK }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image

      - name: Install PaddleFleet
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          source /root/proxy
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleFleet/${BRANCH}/${PR_ID}/${COMMIT_ID}/PaddleFleet.tar.gz --no-check-certificate
          echo "Extracting PaddleFleet.tar.gz"
          tar -xf PaddleFleet.tar.gz --strip-components=1
          rm PaddleFleet.tar.gz
          git config --global --add safe.directory /workspace
          sed -i "s#packages/nightly/cu129#packages/nightly/${{ matrix.cuda.bos_CUDA }}#g" pyproject.toml
          cat pyproject.toml
          mkdir -p /root/.cache/pip
          pip cache dir
          pip install --break-system-packages --upgrade pip
          pip install --break-system-packages uv
          python -m pip install --break-system-packages bce-python-sdk==0.8.74
          '

      - name: Build wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          export UV_PYTHON=${{ matrix.python_version }}
          source /root/proxy
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            VERSION="${TAG_NAME#v}"
            export PADDLEFLEET_VERSION=$VERSION
          fi
          export IS_NVIDIA=True
          uv build --wheel -v --python /usr/bin/python
          '

      - name: Upload wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/nightly/${{ matrix.cuda.bos_CUDA }}/paddlefleet
            export AK=paddle
            export SK=paddle
            python ../bos/BosClient.py paddlefleet-*.whl paddle-github-action/PaddleFleet/${BRANCH}/${COMMIT_ID}
            PY_VERSION="${{ matrix.python_version }}"
            PY_VERSION_SHORT="${PY_VERSION//./}"
            mv paddlefleet-*.whl paddlefleet-0.0.0-py3-none-linux_aarch64.whl
            python ../bos/BosClient.py paddlefleet-0.0.0-py3-none-linux_aarch64.whl paddle-github-action/PaddleFleet/${BRANCH}/latest
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            python ../bos/BosClient.py paddlefleet-*.whl paddle-whl/stable/${{ matrix.cuda.bos_CUDA }}/paddlefleet
          fi
          curl https://www.paddlepaddle.org.cn/inner/whl/update/path/new
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
