name: Test-release3.3

on:
  pull_request:
    branches:
      - develop
      - release/**

permissions: read-all



concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  work_dir: /paddle
  PADDLE_ROOT: /paddle
  ci_scripts: /paddle/ci
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}
  CI_name: test
  no_proxy: "bcebos.com,.bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
  docker_image: "ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:cuda126-dev"
  paddle_url: "https://paddle-qa.bj.bcebos.com/paddle-pipeline/Release-TagBuild-Training-Linux-Gpu-Cuda12.6-Cudnn9.5-Trt10.5-Mkl-Avx-Gcc11-SelfBuiltPypiUse/cbf3469113cd76b7d5f4cba7b8d7d5f55d9e9911/paddlepaddle_gpu-3.3.0-cp310-cp310-linux_x86_64.whl"
  paddlefleet_url: "https://paddle-github-action.cdn.bcebos.com/PaddleFleet/release/0.1.0/latest/cu126/paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl"

defaults:
  run:
    shell: bash

jobs:
  integration-test-a100:
    name: Integration test (A100)
    runs-on:
      group: Distribute
    env:
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      TASK: paddlefleet-CE-CUDA126-RELEASE-integration-test-A100-release
    steps:
      - name: Check docker image and run container
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker pull $docker_image
          docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}/../../..:/root \
            -v /ssd1/paddle-1/action_cache:/home/.cache \
            -v ${{ github.workspace }}:/workspace \
            -e BRANCH \
            -e PR_ID \
            -e paddle_url \
            -e paddlefleet_url \
            -e COMMIT_ID \
            -e PADDLE_ROOT \
            -e ci_scripts \
            -e CACHE_DIR \
            -e no_proxy \
            -e CI_name \
            -e PIP_CACHE_DIR \
            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
            -e GITHUB_REPO_NAME="${{ github.repository }}" \
            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_RUN_ID="${{ github.run_id }}" \
            -w /workspace --network host ${docker_image}

      - name: Install PaddleFleet
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          rm -rf * .[^.]*
          set -x
          source /root/proxy
          mkdir -p /home/.cache/pip
          pip cache dir
          pip install --upgrade pip
          git clone https://github.com/PaddlePaddle/PaddleFleet.git
          cd PaddleFleet
          git config --global --add safe.directory /workspace/PaddleFleet
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git pull --no-edit origin pull/${PR_ID}/head
          pip install colorlog>=6.10.1
          pip uninstall paddlefleet -y
          wget $paddlefleet_url -O paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl
          pip install paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu126/
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          '

      - name: Install PaddleFormers
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          set -x
          source /root/proxy
          git clone https://github.com/PaddlePaddle/PaddleFormers.git
          cd PaddleFormers
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git checkout c17cad10329e512b105f41c19fe14475bc012d55
          sed -i -e '15a\' -e 'import importlib.metadata' paddleformers/utils/import_utils.py
          # git log -1
          pip install -e . --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu126/
          pip install uv coverage==7.6.1 bce-python-sdk==0.8.74 wrapt
          pip install bce-python-sdk==0.8.74
          pip install coverage==7.6.1
          pip install librosa==0.11.0
          echo "Paddle Commit"
          python -c "import paddle; print(paddle.version.commit)"
          echo "PaddleFleet Commit"
          python -c "import paddlefleet; print(paddlefleet.version.commit)"
          '

      - name: GLM4.5 pre-train
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          bash -x PaddleFormers/tests/integration_test/glm45_pt_a100.sh
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
          fi
          '


      - name: Terminate and delete the container
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash PaddleFleet/ci/clean_uv_cache.sh; rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
